[package]
name = "rs-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.146"
tokio = { version = "1.48.0", features = ["rt-multi-thread", "io-std", "macros"] }
tower-lsp = "0.20.0"
tracing-subscriber = "0.3.22"
